openapi: 3.0.0
info:
  title: Viking Vengeance Currency API
  description: API endpoints for gold, gems, and pack purchasing
  version: 1.0.0

paths:
  /api/currency:
    get:
      summary: Get user's current currencies
      description: Get current currency balances for the authenticated user
      tags:
        - Currency
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Currencies retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gold:
                    type: integer
                    description: Gold balance
                  gems:
                    type: integer
                    description: Gems balance
                  total_xp:
                    type: integer
                    description: Total XP balance
                  in_game_currency:
                    type: integer
                    description: Legacy field for backward compatibility
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/currency/pack-prices:
    get:
      summary: Get pack prices
      description: Get current pack prices in different currencies
      tags:
        - Currency
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Pack prices retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gold:
                    type: integer
                    description: Cost in gold per pack
                    example: 50
                  gems:
                    type: integer
                    description: Cost in gems per pack
                    example: 5
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/currency/purchase-packs:
    post:
      summary: Purchase packs with currency
      description: Purchase packs using gold or gems
      tags:
        - Currency
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - packType
                - quantity
                - currency
              properties:
                packType:
                  type: string
                  description: Type of pack to purchase
                quantity:
                  type: integer
                  minimum: 1
                  description: Number of packs to purchase
                currency:
                  type: string
                  enum: [gold, gems]
                  description: Currency to use for purchase
      responses:
        "200":
          description: Packs purchased successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  purchase_details:
                    type: object
                    properties:
                      quantity:
                        type: integer
                        description: Number of packs purchased
                      currency_type:
                        type: string
                        enum: [gold, gems]
                        description: Currency type used
                      cost_per_pack:
                        type: integer
                        description: Cost per individual pack
                      total_cost:
                        type: integer
                        description: Total cost of the purchase
                  updated_currencies:
                    type: object
                    properties:
                      gold:
                        type: integer
                        description: Updated gold balance
                      gems:
                        type: integer
                        description: Updated gems balance
                      pack_count:
                        type: integer
                        description: Updated pack count
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "402":
          $ref: "#/components/responses/InsufficientFundsError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/currency/award:
    post:
      summary: Award currency to user
      description: Award currency to the authenticated user (admin or achievement system)
      tags:
        - Currency
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currency
                - amount
              properties:
                currency:
                  type: string
                  enum: [gold, gems, fate_coins]
                  description: Type of currency to award
                amount:
                  type: integer
                  minimum: 1
                  description: Amount of currency to award
                reason:
                  type: string
                  description: Reason for the award
      responses:
        "200":
          description: Currency awarded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
                    description: Reason for the currency award
                    example: "Manual award"
                  updated_currencies:
                    type: object
                    properties:
                      gold:
                        type: integer
                        description: Updated gold balance
                      gems:
                        type: integer
                        description: Updated gems balance
                      total_xp:
                        type: integer
                        description: Updated total XP balance
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserCurrencies:
      type: object
      properties:
        gold:
          type: integer
          description: Gold balance
        gems:
          type: integer
          description: Gems balance
        fate_coins:
          type: integer
          description: Fate coins balance

    PackPrice:
      type: object
      properties:
        pack_type:
          type: string
        set_name:
          type: string
        gold_price:
          type: integer
          nullable: true
        gems_price:
          type: integer
          nullable: true

    PackPurchase:
      type: object
      properties:
        purchase_id:
          type: string
        pack_type:
          type: string
        quantity:
          type: integer
        currency_used:
          type: string
        total_cost:
          type: integer
        purchased_at:
          type: string
          format: date-time

    CurrencyAward:
      type: object
      properties:
        award_id:
          type: string
        currency:
          type: string
        amount:
          type: integer
        reason:
          type: string
        awarded_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
            suggestion:
              type: string

  responses:
    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InsufficientFundsError:
      description: Insufficient funds
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
