openapi: 3.0.0
info:
  title: Viking Vengeance Leaderboard API
  description: API endpoints for rankings and competitive features
  version: 1.0.0

paths:
  /api/leaderboard:
    get:
      summary: Get current leaderboard
      description: Get current leaderboard with optional user context
      tags:
        - Leaderboard
      parameters:
        - name: season
          in: query
          description: Specific season to view
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Results per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        "200":
          description: Leaderboard retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  leaderboard:
                    type: array
                    items:
                      $ref: "#/components/schemas/LeaderboardEntry"
                  user_rank:
                    type: integer
                    nullable: true
                    description: Current user's rank (if authenticated)
                  user_info:
                    $ref: "#/components/schemas/LeaderboardEntry"
                    nullable: true
                    description: Current user's info (if authenticated)
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_players:
                        type: integer
                      per_page:
                        type: integer
                  season_info:
                    type: object
                    properties:
                      current_season:
                        type: string
                      season_start:
                        type: string
                        format: date-time
                      season_end:
                        type: string
                        format: date-time
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/stats:
    get:
      summary: Get leaderboard statistics
      description: Get leaderboard statistics and tier distribution
      tags:
        - Leaderboard
      parameters:
        - name: season
          in: query
          description: Specific season to view
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Leaderboard statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  stats:
                    type: object
                    properties:
                      total_players:
                        type: integer
                      total_games:
                        type: integer
                      average_rating:
                        type: number
                      tier_distribution:
                        type: object
                        additionalProperties:
                          type: integer
                      top_players_by_tier:
                        type: object
                        additionalProperties:
                          type: array
                          items:
                            $ref: "#/components/schemas/LeaderboardEntry"
                  season:
                    type: string
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/me:
    get:
      summary: Get user's ranking information
      description: Get current user's detailed ranking information
      tags:
        - Leaderboard
      security:
        - bearerAuth: []
      parameters:
        - name: season
          in: query
          description: Specific season to view
          required: false
          schema:
            type: string
      responses:
        "200":
          description: User ranking retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_ranking:
                    $ref: "#/components/schemas/UserRanking"
                  rank_position:
                    type: integer
                    description: User's current rank position
                  rank_progress:
                    type: object
                    properties:
                      current_tier:
                        type: string
                      next_tier:
                        type: string
                        nullable: true
                      rating_needed_for_next_tier:
                        type: integer
                        nullable: true
                      progress_percentage:
                        type: integer
                  recent_games:
                    type: array
                    items:
                      type: object
                  season:
                    type: string
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/me/history:
    get:
      summary: Get user's rank history
      description: Get user's rank history across seasons
      tags:
        - Leaderboard
      security:
        - bearerAuth: []
      parameters:
        - name: seasons
          in: query
          description: Specific seasons to include
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Rank history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  rank_history:
                    type: array
                    items:
                      type: object
                      properties:
                        season:
                          type: string
                        rating:
                          type: integer
                        peak_rating:
                          type: integer
                        rank_tier:
                          type: string
                        wins:
                          type: integer
                        losses:
                          type: integer
                        draws:
                          type: integer
                        current_rank:
                          type: integer
                          nullable: true
                        peak_rank:
                          type: integer
                          nullable: true
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/me/around:
    get:
      summary: Get leaderboard around user
      description: Get leaderboard around current user's position
      tags:
        - Leaderboard
      security:
        - bearerAuth: []
      parameters:
        - name: season
          in: query
          description: Specific season to view
          required: false
          schema:
            type: string
        - name: range
          in: query
          description: Players above/below user
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 25
            default: 10
      responses:
        "200":
          description: Contextual leaderboard retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  leaderboard:
                    type: array
                    items:
                      $ref: "#/components/schemas/LeaderboardEntry"
                  user_position:
                    type: integer
                    description: User's position in the leaderboard
                  context_range:
                    type: object
                    properties:
                      start_rank:
                        type: integer
                      end_rank:
                        type: integer
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/user/{identifier}:
    get:
      summary: Get public user ranking
      description: Get public ranking for a specific user
      tags:
        - Leaderboard
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
          description: Username or user ID
        - name: season
          in: query
          description: Specific season to view
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Public user ranking retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_ranking:
                    type: object
                    properties:
                      username:
                        type: string
                      rating:
                        type: integer
                      rank_tier:
                        type: string
                      wins:
                        type: integer
                      losses:
                        type: integer
                      draws:
                        type: integer
                      total_games:
                        type: integer
                      win_rate:
                        type: number
                      current_rank:
                        type: integer
                      peak_rank:
                        type: integer
                      peak_rating:
                        type: integer
                  rank_position:
                    type: integer
                  rank_progress:
                    type: object
                    properties:
                      current_tier:
                        type: string
                      next_tier:
                        type: string
                        nullable: true
                      rating_needed_for_next_tier:
                        type: integer
                        nullable: true
                      progress_percentage:
                        type: integer
                  recent_games:
                    type: array
                    items: {}
                    description: Empty array for privacy
                  season:
                    type: string
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/leaderboard/me/initialize:
    post:
      summary: Initialize user ranking
      description: Initialize user ranking for current/specific season
      tags:
        - Leaderboard
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                season:
                  type: string
                  description: Season to initialize for
      responses:
        "200":
          description: User ranking initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_ranking:
                    $ref: "#/components/schemas/UserRanking"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LeaderboardEntry:
      type: object
      properties:
        rank:
          type: integer
        user_id:
          type: string
        username:
          type: string
        rating:
          type: integer
        tier:
          type: string
        wins:
          type: integer
        losses:
          type: integer
        games_played:
          type: integer
        win_rate:
          type: number
        streak:
          type: integer
        last_played:
          type: string
          format: date-time

    UserRanking:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        rank:
          type: integer
        rating:
          type: integer
        tier:
          type: string
        wins:
          type: integer
        losses:
          type: integer
        games_played:
          type: integer
        win_rate:
          type: number
        streak:
          type: integer
        season:
          type: string
        last_played:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    PublicUserRanking:
      type: object
      properties:
        username:
          type: string
        rank:
          type: integer
        rating:
          type: integer
        tier:
          type: string
        games_played:
          type: integer
        win_rate:
          type: number
        season:
          type: string

    SeasonRanking:
      type: object
      properties:
        season:
          type: string
        rank:
          type: integer
        rating:
          type: integer
        tier:
          type: string
        games_played:
          type: integer
        wins:
          type: integer
        losses:
          type: integer

    LeaderboardStats:
      type: object
      properties:
        total_players:
          type: integer
        tier_distribution:
          type: object
          additionalProperties:
            type: integer
        average_rating:
          type: number
        season:
          type: string

    PaginationInfo:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        pages:
          type: integer

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
            suggestion:
              type: string

  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFoundError:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
