openapi: 3.0.0
info:
  title: Viking Vengeance - User Card API
  description: API endpoints for managing user's card collection
  version: 1.0.0

paths:
  /api/users/me/cards:
    get:
      summary: Get all cards owned by the authenticated user
      description: Retrieves a list of card instances owned by the currently authenticated user
      tags:
        - User Cards
      security:
        - bearerAuth: []
      parameters:
        - name: rarity
          in: query
          description: Filter by card rarity (e.g., common, rare)
          required: false
          schema:
            type: string
            enum: [common, uncommon, rare, epic, legendary]
        - name: name
          in: query
          description: Filter by card name (case-insensitive, partial match)
          required: false
          schema:
            type: string
        - name: tag
          in: query
          description: Filter by a specific card tag
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of the user's card instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserCard"
        "401":
          description: Unauthorized - User not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    PowerValues:
      type: object
      properties:
        top:
          type: integer
          example: 5
        right:
          type: integer
          example: 5
        bottom:
          type: integer
          example: 5
        left:
          type: integer
          example: 5
      required:
        - top
        - right
        - bottom
        - left

    SpecialAbility:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        ability_id:
          type: string
          format: uuid
        description:
          type: string
        triggerMoment:
          type: string
          enum: [OnPlace, OnFlip, OnFlipped, OnTurnStart, OnTurnEnd]
        parameters:
          type: object
          description: Additional parameters for the ability
          additionalProperties: true
      required:
        - id
        - name
        - ability_id
        - description
        - triggerMoment
        - parameters

    BaseCardData:
      type: object
      properties:
        card_id:
          type: string
          format: uuid
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        rarity:
          type: string
          enum: [common, uncommon, rare, epic, legendary]
        image_url:
          type: string
        base_power:
          $ref: "#/components/schemas/PowerValues"
        special_ability:
          $ref: "#/components/schemas/SpecialAbility"
          nullable: true
      required:
        - card_id
        - name
        - tags
        - rarity
        - image_url
        - base_power

    UserCard:
      type: object
      description: A card instance owned by a user, including base card data and user-specific enhancements
      properties:
        user_card_instance_id:
          type: string
          format: uuid
          description: Unique identifier for this specific card instance
        base_card_id:
          type: string
          format: uuid
          description: Reference to the base card definition
        base_card_data:
          $ref: "#/components/schemas/BaseCardData"
          description: The complete base card information
        level:
          type: integer
          description: Current level of the card instance
          minimum: 1
        xp:
          type: integer
          description: Current experience points of the card instance
          minimum: 0
        power_enhancements:
          $ref: "#/components/schemas/PowerValues"
          description: Additional power values from leveling up
      required:
        - user_card_instance_id
        - base_card_id
        - base_card_data
        - level
        - xp
        - power_enhancements

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
