/**
 * Deck Effects - Passive abilities based on deck mythology composition
 *
 * Effects:
 * - Norse: Played card gains +1 to all sides when you play while opponent leads
 * - Polynesian: Random card in hand gains +1 when terrain is added (once per round)
 * - Japanese: Random card in hand gains +1 when a card receives a curse (once per round)
 */

import { GameState, Player, DeckEffectType, BoardPosition } from "../types/game.types";
import { InGameCard } from "../types/card.types";
import { BaseGameEvent, CardPowerChangedEvent, EVENT_TYPES } from "../types/game-engine.types";
import { addTempBuff, updateCurrentPower } from "./ability.utils";
import { v4 as uuidv4 } from "uuid";

// Sentinel position for cards in hand (not on board)
const HAND_POSITION: BoardPosition = { x: -1, y: -1 };

/**
 * Calculate the current round number from turn number.
 * Each round consists of 2 turns (one per player).
 */
export function getCurrentRound(turnNumber: number): number {
  return Math.ceil(turnNumber / 2);
}

/**
 * Calculate score on the fly by counting board cards owned by each player.
 * This avoids needing to maintain score state during gameplay.
 */
export function calculateScoreOnTheFly(
  gameState: GameState,
  playerId: string
): { playerScore: number; opponentScore: number } {
  let playerScore = 0;
  let opponentScore = 0;

  for (const row of gameState.board) {
    for (const cell of row) {
      if (cell.card) {
        if (cell.card.owner === playerId) {
          playerScore++;
        } else {
          opponentScore++;
        }
      }
    }
  }

  return { playerScore, opponentScore };
}

/**
 * Check if opponent is currently leading (has more cards on board).
 */
export function isOpponentLeading(
  gameState: GameState,
  playerId: string
): boolean {
  const { playerScore, opponentScore } = calculateScoreOnTheFly(
    gameState,
    playerId
  );
  return opponentScore > playerScore;
}

/**
 * Get a random card from a player's hand.
 * Returns null if hand is empty.
 */
export function getRandomHandCard(
  gameState: GameState,
  playerId: string
): InGameCard | null {
  const player =
    gameState.player1.user_id === playerId
      ? gameState.player1
      : gameState.player2;

  if (player.hand.length === 0) {
    return null;
  }

  const randomIndex = Math.floor(Math.random() * player.hand.length);
  const cardId = player.hand[randomIndex];

  return gameState.hydrated_card_data_cache?.[cardId] || null;
}

/**
 * Get the player object from the game state.
 */
export function getPlayer(gameState: GameState, playerId: string): Player {
  return gameState.player1.user_id === playerId
    ? gameState.player1
    : gameState.player2;
}

/**
 * Apply the Norse deck effect: +1 to all sides of the placed card when opponent leads.
 * This should be called BEFORE the card is placed on the board (while checking score).
 *
 * @returns Events generated by the effect, or empty array if not triggered
 */
export function applyNorseDeckEffect(
  gameState: GameState,
  playerId: string,
  placedCard: InGameCard
): BaseGameEvent[] {
  const player = getPlayer(gameState, playerId);

  // Check if player has Norse deck effect
  if (player.deck_effect !== "norse") {
    return [];
  }

  // Check if opponent is leading BEFORE this card is placed
  if (!isOpponentLeading(gameState, playerId)) {
    return [];
  }

  // Apply +1 buff to all sides of the placed card
  // Card is being placed, use HAND_POSITION as the buff is applied before board placement
  const events: BaseGameEvent[] = [];
  events.push(
    addTempBuff(placedCard, 1000, 1, {
      name: "Norse Deck Bonus",
      animation: "norse-deck-effect",
      position: HAND_POSITION,
    })
  );

  // Update the card's current power
  placedCard.current_power = updateCurrentPower(placedCard);

  // Also update in the cache if present
  if (
    gameState.hydrated_card_data_cache &&
    gameState.hydrated_card_data_cache[placedCard.user_card_instance_id]
  ) {
    gameState.hydrated_card_data_cache[placedCard.user_card_instance_id] =
      placedCard;
  }

  return events;
}

/**
 * Apply the Polynesian deck effect: +1 to a random card in hand when terrain is added.
 * This is a once-per-round effect.
 *
 * @param actingPlayerId - The player who triggered the terrain effect (either player can trigger it)
 * @returns Events generated by the effect, or empty array if not triggered
 */
export function applyPolynesianDeckEffect(
  gameState: GameState,
  beneficiaryPlayerId: string
): BaseGameEvent[] {
  const player = getPlayer(gameState, beneficiaryPlayerId);

  // Check if player has Polynesian deck effect
  if (player.deck_effect !== "polynesian") {
    return [];
  }

  // Check once-per-round limit
  const currentRound = getCurrentRound(gameState.turn_number);
  if (
    player.deck_effect_state &&
    player.deck_effect_state.last_triggered_round >= currentRound
  ) {
    return [];
  }

  // Get a random card from the player's hand
  const randomCard = getRandomHandCard(gameState, beneficiaryPlayerId);
  if (!randomCard) {
    return [];
  }

  // Update the trigger state
  if (!player.deck_effect_state) {
    player.deck_effect_state = { last_triggered_round: 0 };
  }
  player.deck_effect_state.last_triggered_round = currentRound;

  // Apply +1 buff to the random hand card
  const events: BaseGameEvent[] = [];
  events.push(
    addTempBuff(randomCard, 1000, 1, {
      name: "Polynesian Deck Bonus",
      animation: "polynesian-deck-effect",
      position: HAND_POSITION,
    })
  );

  // Update the card's current power
  randomCard.current_power = updateCurrentPower(randomCard);

  // Also update in the cache if present
  if (
    gameState.hydrated_card_data_cache &&
    gameState.hydrated_card_data_cache[randomCard.user_card_instance_id]
  ) {
    gameState.hydrated_card_data_cache[randomCard.user_card_instance_id] =
      randomCard;
  }

  // Add a specific event to notify the client about the deck effect
  events.push({
    type: EVENT_TYPES.CARD_POWER_CHANGED,
    eventId: uuidv4(),
    timestamp: Date.now(),
    cardId: randomCard.user_card_instance_id,
    animation: "polynesian-deck-effect",
    sourcePlayerId: beneficiaryPlayerId,
    powerDelta: 1,
    effectName: "Polynesian Deck Bonus",
    position: HAND_POSITION,
  } as CardPowerChangedEvent);

  return events;
}

/**
 * Apply the Japanese deck effect: +1 to a random card in hand when a card receives a curse.
 * This is a once-per-round effect.
 *
 * @returns Events generated by the effect, or empty array if not triggered
 */
export function applyJapaneseDeckEffect(
  gameState: GameState,
  beneficiaryPlayerId: string
): BaseGameEvent[] {
  const player = getPlayer(gameState, beneficiaryPlayerId);

  // Check if player has Japanese deck effect
  if (player.deck_effect !== "japanese") {
    return [];
  }

  // Check once-per-round limit
  const currentRound = getCurrentRound(gameState.turn_number);
  if (
    player.deck_effect_state &&
    player.deck_effect_state.last_triggered_round >= currentRound
  ) {
    return [];
  }

  // Get a random card from the player's hand
  const randomCard = getRandomHandCard(gameState, beneficiaryPlayerId);
  if (!randomCard) {
    return [];
  }

  // Update the trigger state
  if (!player.deck_effect_state) {
    player.deck_effect_state = { last_triggered_round: 0 };
  }
  player.deck_effect_state.last_triggered_round = currentRound;

  // Apply +1 buff to the random hand card
  const events: BaseGameEvent[] = [];
  events.push(
    addTempBuff(randomCard, 1000, 1, {
      name: "Japanese Deck Bonus",
      animation: "japanese-deck-effect",
      position: HAND_POSITION,
    })
  );

  // Update the card's current power
  randomCard.current_power = updateCurrentPower(randomCard);

  // Also update in the cache if present
  if (
    gameState.hydrated_card_data_cache &&
    gameState.hydrated_card_data_cache[randomCard.user_card_instance_id]
  ) {
    gameState.hydrated_card_data_cache[randomCard.user_card_instance_id] =
      randomCard;
  }

  // Add a specific event to notify the client about the deck effect
  events.push({
    type: EVENT_TYPES.CARD_POWER_CHANGED,
    eventId: uuidv4(),
    timestamp: Date.now(),
    cardId: randomCard.user_card_instance_id,
    animation: "japanese-deck-effect",
    sourcePlayerId: beneficiaryPlayerId,
    powerDelta: 1,
    effectName: "Japanese Deck Bonus",
    position: HAND_POSITION,
  } as CardPowerChangedEvent);

  return events;
}

/**
 * Check all players for Polynesian deck effect and apply if terrain was added.
 * Called when a terrain effect is added to a tile.
 */
export function triggerTerrainDeckEffects(
  gameState: GameState
): BaseGameEvent[] {
  const events: BaseGameEvent[] = [];

  // Check both players for Polynesian deck effect
  events.push(...applyPolynesianDeckEffect(gameState, gameState.player1.user_id));
  events.push(...applyPolynesianDeckEffect(gameState, gameState.player2.user_id));

  return events;
}

/**
 * Check all players for Japanese deck effect and apply if a card received a curse.
 * Called when a card receives a curse effect from a tile.
 */
export function triggerCurseDeckEffects(
  gameState: GameState
): BaseGameEvent[] {
  const events: BaseGameEvent[] = [];

  // Check both players for Japanese deck effect
  events.push(...applyJapaneseDeckEffect(gameState, gameState.player1.user_id));
  events.push(...applyJapaneseDeckEffect(gameState, gameState.player2.user_id));

  return events;
}
