import { BoardCell, BoardPosition } from "../types";

export const EVENT_TYPES = {
  GAME_START: "GAME_START",
  TURN_START: "TURN_START",
  CARD_DRAWN: "CARD_DRAWN",
  CARD_PLACED: "CARD_PLACED",
  ABILITY_TRIGGERED: "ABILITY_TRIGGERED",
  CARD_POWER_CHANGED: "CARD_POWER_CHANGED",
  CARD_FLIPPED: "CARD_FLIPPED",
  TILE_STATE_CHANGED: "TILE_STATE_CHANGED",
  CARD_STATE_CHANGED: "CARD_STATE_CHANGED",
  SCORE_UPDATED: "SCORE_UPDATED",
  TURN_END: "TURN_END",
  GAME_OVER: "GAME_OVER",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  STATUS_EFFECT_APPLIED: "STATUS_EFFECT_APPLIED",
  STATUS_EFFECT_REMOVED: "STATUS_EFFECT_REMOVED",
  CARD_MOVED: "CARD_MOVED",
  CARD_REMOVED_FROM_BOARD: "CARD_REMOVED_FROM_BOARD",
  CARD_REMOVED_FROM_HAND: "CARD_REMOVED_FROM_HAND",
} as const;

export type GameEventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export interface BaseGameEvent {
  type: string; // Discriminator for the event type (e.g., "CARD_PLACED", "CARD_FLIPPED")
  eventId: string; // A unique ID for this event instance (e.g., UUID generated by server)
  timestamp: number; // Server timestamp (milliseconds since epoch) when the event was processed
  delayAfterMs?: number; // Optional: Suggested delay in milliseconds before processing the next event (for animation pacing)
  sourcePlayerId?: string; // Optional: The player ID that initiated or caused this event
  animation?: string; // Optional: The animation to play for the event
}

export interface CardEvent extends BaseGameEvent {
  cardId: string;
}

export interface CardPlacedEvent extends CardEvent {
  originalOwner: string;
  position: BoardPosition;
}

export interface TileEvent extends BaseGameEvent {
  position: BoardPosition;
  tile: Pick<BoardCell, "tile_status" | "turns_left" | "animation_label">;
}

export function batchEvents(
  events: BaseGameEvent[],
  delay: number
): BaseGameEvent[] {
  if (events.length > 0) {
    events[events.length - 1].delayAfterMs = delay;
  }
  return events;
}
