// scripts/game-data.js
const SPECIAL_ABILITIES_DATA = [
  {
    id: "gungnir_strike",
    name: "Gungnir Strike",
    description:
      "OnPlace: If opponent has more cards, gain +2 power in all directions.",
    triggerMoment: "OnPlace",
    parameters: {
      condition: "opponent_more_cards",
      effect: "buff_all",
      value: 2,
    },
  },
  {
    id: "shield_wall",
    name: "Shield Wall",
    description: "This card cannot be flipped for 1 turn after placement.",
    triggerMoment: "OnPlace",
    parameters: { effect: "temporary_immunity", duration: 1 },
  },
  {
    id: "berserker_rage",
    name: "Berserker Rage",
    description: "OnFlipped: The card that flipped this one loses 2 power.",
    triggerMoment: "OnFlipped",
    parameters: { effect: "debuff_flipper", value: 2 },
  },
  {
    id: "valkyrie_blessing",
    name: "Valkyrie's Blessing",
    description: "OnPlace: Adjacent friendly cards gain +1 power.",
    triggerMoment: "OnPlace",
    parameters: { effect: "buff_adjacent", value: 1 },
  },
  {
    id: "ragnarok",
    name: "Ragnarok",
    description: "OnPlace: Flip a random enemy card.",
    triggerMoment: "OnPlace",
    parameters: { effect: "flip_random_enemy" },
  },
  {
    id: "fate_weaving",
    name: "Fate Weaving",
    description: "OnTurnStart: 25% chance to gain +1 power each turn.",
    triggerMoment: "OnTurnStart",
    parameters: { effect: "chance_buff", chance: 25, value: 1 },
  },
];

const CARDS_DATA = [
  {
    id_placeholder: "odin",
    name: "Odin, Allfather",
    type: "God",
    rarity: "legendary",
    imageUrl: "assets/cards/odin.png",
    power: { top: 8, right: 5, bottom: 3, left: 9 },
    specialAbilityId: "gungnir_strike",
    tags: ["aesir", "leader"],
  },
  {
    id_placeholder: "freya",
    name: "Freya, Vanadis",
    type: "Goddess",
    rarity: "epic",
    imageUrl: "assets/cards/freya.png",
    power: { top: 6, right: 6, bottom: 4, left: 7 },
    specialAbilityId: "fate_weaving",
    tags: ["vanir", "magic"],
  },
  {
    id_placeholder: "thor",
    name: "Thor, Thunder God",
    type: "God",
    rarity: "legendary",
    imageUrl: "assets/cards/thor.png",
    power: { top: 9, right: 7, bottom: 6, left: 4 },
    specialAbilityId: "berserker_rage",
    tags: ["aesir", "warrior"],
  },
  {
    id_placeholder: "loki",
    name: "Loki, Trickster",
    type: "God",
    rarity: "epic",
    imageUrl: "assets/cards/loki.png",
    power: { top: 3, right: 8, bottom: 7, left: 5 },
    specialAbilityId: "ragnarok",
    tags: ["jotun", "trickster"],
  },
  {
    id_placeholder: "heimdall",
    name: "Heimdall, Watchman",
    type: "God",
    rarity: "rare",
    imageUrl: "assets/cards/heimdall.png",
    power: { top: 7, right: 4, bottom: 5, left: 8 },
    specialAbilityId: "shield_wall",
    tags: ["aesir", "guardian"],
  },
  {
    id_placeholder: "valkyrie",
    name: "Valkyrie",
    type: "Divine",
    rarity: "uncommon",
    imageUrl: "assets/cards/valkyrie.png",
    power: { top: 5, right: 5, bottom: 5, left: 5 },
    specialAbilityId: "valkyrie_blessing",
    tags: ["aesir", "warrior"],
  },
  {
    id_placeholder: "fenrir",
    name: "Fenrir, Great Wolf",
    type: "Beast",
    rarity: "rare",
    imageUrl: "assets/cards/fenrir.png",
    power: { top: 8, right: 6, bottom: 5, left: 4 },
    specialAbilityId: null,
    tags: ["beast", "jotun"],
  },
  {
    id_placeholder: "jormungandr",
    name: "Jormungandr, World Serpent",
    type: "Beast",
    rarity: "epic",
    imageUrl: "assets/cards/jormungandr.png",
    power: { top: 6, right: 6, bottom: 8, left: 6 },
    specialAbilityId: null,
    tags: ["beast", "jotun"],
  },
  {
    id_placeholder: "hel",
    name: "Hel, Death Goddess",
    type: "Goddess",
    rarity: "epic",
    imageUrl: "assets/cards/hel.png",
    power: { top: 4, right: 7, bottom: 7, left: 5 },
    specialAbilityId: null,
    tags: ["jotun", "underworld"],
  },
  {
    id_placeholder: "viking_warrior",
    name: "Viking Warrior",
    type: "Human",
    rarity: "common",
    imageUrl: "assets/cards/viking_warrior.png",
    power: { top: 4, right: 3, bottom: 4, left: 3 },
    specialAbilityId: null,
    tags: ["human", "warrior"],
  },
];

module.exports = { CARDS_DATA, SPECIAL_ABILITIES_DATA };
